# Sprint 2 – Notebook 1: Introduction to Statistics



 ## What is Stastistics ?
 

Statistics is the process of collecting, organizing, analyzing, interpreting, and communicating data.

### Example :

A machine-learning system might contain thousands of customer records. Statistics can help us understand the data before training a model.
A machine-learning system might contain thousands of customer records. Statistics can help us understand the data before training a model.
    

In [2]:
import numpy as np

scores = np.array([60, 70, 75, 80, 90])

mean_score = np.mean(scores)

print("Scores:", scores)
print("Average score:", mean_score)


Scores: [60 70 75 80 90]
Average score: 75.0


## Why Statistics is Important in AI/ML ?

Machine learning works with data. Statistics gives us tools to understand that data before, during, and after model development.

Statistics helps an AI/ML engineer:
- Understand datasets
- Find patterns
- Detect unusual values
- Measure relationships between variables
- Handle missing values
- Evaluate models
- Estimate uncertainty
- Test hypotheses
- Understand model performance

### Example :
Imagine a company wants to predict whether customers will purchase a product.
| Age | Income | Previous Purchases | Purchased |
|---:|---:|---:|---|
| 22 | 25000 | 1 | No |
| 28 | 35000 | 2 | No |
| 35 | 50000 | 5 | Yes |
| 42 | 70000 | 8 | Yes |

In [4]:
import pandas as pd

data = {
    "Age": [22, 28, 35, 42],
    "Income": [25000, 35000, 50000, 70000],
    "Previous_Purchases": [1, 2, 5, 8],
    "Purchased": ["No", "No", "Yes", "Yes"]
}

df = pd.DataFrame(data)

print(df)

print("\nAverage Age:", df["Age"].mean())
print("Average Income:", df["Income"].mean())

   Age  Income  Previous_Purchases Purchased
0   22   25000                   1        No
1   28   35000                   2        No
2   35   50000                   5       Yes
3   42   70000                   8       Yes

Average Age: 31.75
Average Income: 45000.0


## Statistics vs Machine Learning

Statistics and machine learning both work with data, but their primary goals can be different.
### Statistics
Statistics often focuses on:
Understanding data and drawing conclusions from it.

Statistics → Understand

Machine Learning → Predict

#### Example:
- What is the average?
- Is there a relationship between two variables?
- Is this difference statistically significant?
- What can we conclude about a population?
### Machine Learning
Machine learning often focuses on:
Learning patterns from data to make predictions or decisions.

#### Example:
- Will this customer purchase?
- What will tomorrow's sales be?
- Is this image a cat or dog?
- Is this transaction potentially fraudulent?
They overlap heavily. Statistical concepts are used throughout machine learning.

In [5]:
import numpy as np

house_size = np.array([500, 800, 1000, 1200, 1500])
house_price = np.array([20, 30, 40, 48, 60])

correlation = np.corrcoef(house_size, house_price)[0, 1]

print("Correlation:", correlation)

Correlation: 0.9984809174508349


## Descriptive Statistics

Descriptive statistics is the branch of statistics used to organize, summarize, and describe data in a clear and meaningful way
    
Common descriptive statistics include:
- Mean
- Median
- Mode
- Minimum
- Maximum
- Range
- Variance
- Standard deviation
- Percentiles  
### Example :
instead of displaying 10,000 employee salaries individually, we can summarize them using:
Average salary = ₹45,000

Minimum salary = ₹20,000

Maximum salary = ₹90,000

The program calculates several descriptive statistics

A higher standard deviation means the values are more spread out around the mean.

Descriptive statistics are commonly used during Exploratory Data Analysis (EDA) before model training.

In [9]:
import numpy as np

sales = np.array([100, 120, 150, 130, 200])

print("Mean:", np.mean(sales))
print("Median:", np.median(sales))
print("Minimum:", np.min(sales))
print("Maximum:", np.max(sales))
print("Range:", np.max(sales) - np.min(sales))
print("Standard Deviation:", np.std(sales))

Mean: 140.0
Median: 130.0
Minimum: 100
Maximum: 200
Range: 100
Standard Deviation: 34.058772731852805


## Inferential Statistics

Inferential statistics is a branch of statistics used to make conclusions, predictions, or decisions about a larger population using data collected from a smaller sample.
We can use statistical methods to estimate or test claims about the larger student population.

Important concepts include:
- Sampling
- Confidence intervals
- Hypothesis testing
- Statistical significance
- Probability distributions
 ### Example:

In [11]:
import numpy as np

np.random.seed(42)

population = np.random.normal(70, 10, 10000)

sample = np.random.choice(population, size=100)

print("Population mean:", np.mean(population))
print("Sample mean:", np.mean(sample))

Population mean: 69.97864016631574
Sample mean: 69.90706695486644


## Population

In statistics, a population means the complete group of people, objects, events, or observations that we want to study or draw conclusions about.
### Example:
- All customers of a company
- All students in a university
- All transactions made in a year
- All vehicles produced by a factory
  

In [13]:
import numpy as np

population_salaries = np.array([
    25000, 30000, 35000, 40000, 45000,
    50000, 55000, 60000, 65000, 70000
])

population_mean = np.mean(population_salaries)

print("Population mean salary:", population_mean)

Population mean salary: 47500.0


## Sample
A sample is a smaller group selected from a larger population for the purpose of collecting and analyzing data.
### Example:
Suppose an e-commerce company has one million customers.
Studying every customer may be expensive.
The company randomly selects 5,000 customers and studies their purchasing behavior.
1,000,000 customers → Population
5,000 customers → Sample


In [14]:
import numpy as np

population = np.arange(1, 1001)

sample = np.random.choice(population, size=50, replace=False)

print("Population size:", len(population))
print("Sample size:", len(sample))
print("Sample:", sample)

Population size: 1000
Sample size: 50
Sample: [229  11 290 566 333 600 793 161 784 964 336 267 541 985 395  25 737   1
 378 144 424 833 448 771 924 877 929 217 923 914 435 984  39  12 560 302
 597 239 675 884 905  95 966 274 160 350  61 588  37 418]


## Cencus
A census is a method of collecting data from every member of the entire population being studied.
### Example
If a company has 10,000 employees and collects salary information from all 10,000 employees, it is conducting a census.

Sample → Some members

Census → Every member

In [15]:
import numpy as np

students = np.array([60, 65, 70, 75, 80, 85, 90])

# Census: use every student
census_mean = np.mean(students)

# Sample: use only selected students
sample = students[[0, 2, 4, 6]]
sample_mean = np.mean(sample)

print("Census mean:", census_mean)
print("Sample mean:", sample_mean)

Census mean: 75.0
Sample mean: 75.0


## Sampling

Sampling is the process of selecting a smaller group (sample) from a larger population to collect and analyze data.
Common sampling methods include:
- Simple random sampling
- Systematic sampling
- Stratified sampling
- Cluster sampling
### Simple Example

Suppose a college has 5,000 students and you want to study their study habits.

Population: 5,000 students
Sampling: Selecting 500 students from the 5,000
Sample: The 500 selected student

In [16]:
import numpy as np

np.random.seed(42)

students = np.arange(1, 101)

sample = np.random.choice(
    students,
    size=10,
    replace=False
)

print("Selected sample:")
print(sample)


Selected sample:
[84 54 71 46 45 40 23 81 11  1]


## Variables
A variable is a characteristic, quality, or quantity that can have different values for different people, objects, or observations.
### Example
Age
'Salary
'Gender
'Height
'City
'Number of purchases
| Person | Age | Salary |
|---|---:|---:|
| A | 21 | 25000 |
| B | 25 | 30000 |
| C | 30 | 40000 |

In [17]:
import pandas as pd

data = {
    "Age": [21, 25, 30],
    "Salary": [25000, 30000, 40000]
}

df = pd.DataFrame(data)

print(df)



   Age  Salary
0   21   25000
1   25   30000
2   30   40000


## Features
A feature is an individual measurable property or characteristic of data that is used to describe an observation and, often, to help make predictions.
### Example:
Suppose we want to predict the price of a house:
| House | Area (sq.ft) | Bedrooms | Age (years) | Location | Price |
| ----- | -----------: | -------: | ----------: | -------- | ----: |
| A     |        1,000 |        2 |          10 | Chennai  | ₹50 L |
| B     |        1,500 |        3 |           5 | Chennai  | ₹75 L |
| C     |        2,000 |        4 |           2 | Chennai  | ₹1 Cr |
- Area → Feature
- Number of bedrooms → Feature
- House age → Feature
-Location → Feature
Price → Target/Label (what we want to predict)


In [18]:
import pandas as pd

data = {
    "Area": [1000, 1500, 2000],
    "Bedrooms": [2, 3, 4],
    "Age": [10, 5, 3],
    "Price": [40, 60, 80]
}

df = pd.DataFrame(data)

features = df[["Area", "Bedrooms", "Age"]]
target = df["Price"]

print("Features:")
print(features)

print("\nTarget:")
print(target)


Features:
   Area  Bedrooms  Age
0  1000         2   10
1  1500         3    5
2  2000         4    3

Target:
0    40
1    60
2    80
Name: Price, dtype: int64


## Observation
An observation is a single recorded piece of data or a complete set of information collected about one individual, object, event, or case.

An observation is one row or one data record in a dataset.

### Example

Suppose we collect information about employees
| Age | Salary | Department |
|---:|---:|---|
| 25 | 30000 | IT |
| 28 | 40000 | HR |
- Customer 1 → Observation 1
- Customer 2 → Observation 2
- Customer 3 → Observation 3

In [19]:
import pandas as pd

df = pd.DataFrame({
    "Age": [21, 25, 30],
    "Salary": [25000, 35000, 50000]
})

print("Number of observations:", len(df))

print("\nFirst observation:")
print(df.iloc[0])

Number of observations: 3

First observation:
Age          21
Salary    25000
Name: 0, dtype: int64


## Dataset
A dataset is a collection of related data organized in a structured form, usually in rows and columns, for analysis or machine learning.
A dataset can contain:
- Observations
- Variables
- Features
- Targets
- Labels
### Example:
 | Age | Income | Purchased |
|---:|---:|---|
| 21 | 25000 | No |
| 30 | 50000 | Yes |
| 40 | 70000 | Yes |
- Rows → observations
- Columns → variables/features
- Purchased → target/label
  
An ML dataset for predicting whether an email is spam could contain:

Email length

Number of links

Number of suspicious words

Sender information

Spam/Not Spam


In [22]:
import pandas as pd

dataset = pd.DataFrame({
    "Email_Length": [100, 500, 80, 600],
    "Links": [1, 10, 0, 15],
    "Spam": [0, 1, 0, 1]
})

print(dataset)

print("\nDataset shape:", dataset.shape)

   Email_Length  Links  Spam
0           100      1     0
1           500     10     1
2            80      0     0
3           600     15     1

Dataset shape: (4, 3)


## Quantitative Data
Quantitative data is data that is expressed in numbers and can be measured or counted.
Examples
Age: 21 years
Height: 175 cm
Weight: 60 kg
Salary: ₹30,000
Exam marks: 85
Number of students: 50
Temperature: 32°C
Type of Quantitative data:

1.Discrete Data

Data that can be counted and usually takes whole-number values.

### Examples:

Number of students = 50
Number of cars = 10
Number of employees = 25

2. Continuous Data

Data that can be measured and can take decimal values.

### Examples:

Height = 175.5 cm
Weight = 60.75 kg
Temperature = 32.6°C
Time = 5.25 minutes

### Example:
| Student | Age |   Height | Marks |
| ------- | --: | -------: | ----: |
| A       |  18 | 165.5 cm |    75 |
| B       |  19 | 170.2 cm |    82 |
| C       |  20 | 168.7 cm |    90 |


In [23]:
import numpy as np

ages = np.array([21, 25, 30, 35, 40])

print("Average age:", np.mean(ages))
print("Maximum age:", np.max(ages))
print("Minimum age:", np.min(ages))

Average age: 30.2
Maximum age: 40
Minimum age: 21


## Qualitative Data
Qualitative data is data that describes the qualities, characteristics, categories, or attributes of people, objects, or events.
### Examples
Gender: Male, Female
Blood group: A, B, AB, O
Eye colour: Black, Brown, Blue
Marital status: Single, Married
Product colour: Red, Blue, Green
Customer feedback: Good, Average, Poor

Types of Qualitative Data

1. Nominal Data

Categories that do not have a specific order or ranking.

### Examples:

Blood group: A, B, AB, O
Eye colour: Brown, Black, Blue
Department: IT, Commerce, Mathematics

2. Ordinal Data

Categories that have a meaningful order or ranking.

### Examples:

Satisfaction: Poor → Average → Good → Excellent
Education level: School → Undergraduate → Postgraduate
Rating: 1 star → 2 stars → 3 stars → 4 stars → 5 stars


In [24]:
import pandas as pd

payment_methods = pd.Series([
    "UPI",
    "Card",
    "UPI",
    "Cash",
    "Card",
    "UPI"
])

print(payment_methods.value_counts())

UPI     3
Card    2
Cash    1
Name: count, dtype: int64


## Continuous Data
Continuous data is a type of quantitative data that can take any value within a given range, including decimal and fractional values.
continuous data is data that is measured rather than counted.

### Examples
A person's height could be 170 cm, 170.2 cm, 170.25 cm, or 170.256 cm. There can be many possible values between two numbers.
Continuous variables are common ML features, such as:
- Temperature
- Sensor measurements
- House prices
- Height
- Weight
- Stock prices
| Person |    Height |
| ------ | --------: |
| A      |  165.5 cm |
| B      |  170.2 cm |
| C      | 172.75 cm |
| D      |  168.4 cm |


In [25]:
import numpy as np

temperatures = np.array([
    36.5,
    36.7,
    36.6,
    37.1,
    36.8
])

print("Average temperature:", np.mean(temperatures))
print("Minimum temperature:", np.min(temperatures))
print("Maximum temperature:", np.max(temperatures))

Average temperature: 36.739999999999995
Minimum temperature: 36.5
Maximum temperature: 37.1


## Discrete Data
Discrete data is a type of quantitative data that can be counted and usually takes separate, whole-number values.
### Examples
Number of students: 50
Number of employees: 25
Number of cars: 10
Number of children: 2
Number of books: 15
Number of calls received: 100
| Class | Number of Students |
| ----- | -----------------: |
| A     |                 40 |
| B     |                 35 |
| C     |                 42 |
| D     |                 38 |


In [26]:
import numpy as np

orders = np.array([10, 12, 15, 20, 18])

print("Average orders:", np.mean(orders))
print("Total orders:", np.sum(orders))

Average orders: 15.0
Total orders: 75


## Structured Data
Structured data is data that is organized in a fixed and predefined format, usually in rows and columns.

In structured data is well-organized data that is easy to store, search, and analyze.
### Examples:
- SQL tables
- Excel spreadsheets
- CSV files
- Relational databases
### Example
| Student ID | Name  | Age | Department | Marks |
| ---------- | ----- | --: | ---------- | ----: |
| 101        | Arun  |  20 | BCA        |    85 |
| 102        | Ravi  |  21 | BCA        |    78 |
| 103        | Priya |  20 | B.Com      |    92 |

### Examples of Structured Data
- Excel spreadsheets
- SQL/MySQL databases
- Customer databases
- Employee records
- Bank transaction records
- Student databases
- Inventory systems
  

| ID | Name | Age | Salary |
|---:|---|---:|---:|
| 1 | Arun | 25 | 30000 |
| 2 | Ravi | 28 | 40000 |
| 3 | Kumar | 30 | 50000 |

In [29]:
import pandas as pd

employees = pd.DataFrame({
    "Employee_ID": [101, 102, 103],
    "Name": ["Arun", "Ravi", "Kumar"],
    "Age": [25, 28, 30],
    "Salary": [30000, 40000, 50000]
})

print(employees)

   Employee_ID   Name  Age  Salary
0          101   Arun   25   30000
1          102   Ravi   28   40000
2          103  Kumar   30   50000


## Unstructured Data
Unstructured data is data that does not follow a fixed or predefined format or structure. it is data that is not organized neatly into rows and columns.

### Examples
- Images – photos, medical scans
- Videos – YouTube videos, CCTV footage
- Audio – voice recordings, songs, podcasts
- Text documents – emails, Word documents, PDF files
- Social media posts – comments, posts, messages
- Customer reviews – written feedback
### Example
A customer writes:

"I really like this phone. The camera quality is excellent, but the battery could be better."

This is unstructured text data because it does not follow a fixed table format.



In [30]:
import numpy as np

# Simulate a small grayscale image
image = np.array([
    [0, 255, 100],
    [50, 200, 150],
    [255, 0, 75]
])

print("Image:")
print(image)

print("\nImage shape:", image.shape)
print("Average pixel value:", np.mean(image))

Image:
[[  0 255 100]
 [ 50 200 150]
 [255   0  75]]

Image shape: (3, 3)
Average pixel value: 120.55555555555556
